version: '3'

networks:
  myNetwork:
    driver: bridge

services:
  # client:
  #   # ports: 
  #   #   - 80:80
  #   #   - 443:443
  #   build:
  #     context: .
  #     dockerfile: ./client/Dockerfile
  #   networks:
  #     - myNetwork      
  server:
    # ports: 
    #   - 80:80
    #   - 443:443
    build:
      context: .
      dockerfile: ./server/Dockerfile
    networks:
      - myNetwork        
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - myNetwork    
